name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  APY_KEY: ${{ secrets.API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: echo $API_KEY
